routes:
  /: 
    template: page
    data: page.start
  /en/:
    template: page
    data: page.start-en

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: home
    filter: 'tag:-hash-en+tag:-hash-pressemitteilung'
  /en/blog/:
    permalink: /en/blog/{slug}/
    template: home
    filter: 'tag:hash-en+tag:-hash-pressemitteilung'
  /presse/mitteilungen/:
    permalink: /presse/mitteilungen/{slug}/
    template: index
    filter: 'tag:hash-pressemitteilung'

taxonomies:
  tag: /tag/{slug}/
  author: /autor_in/{slug}/
