routes:
  /: 
    template: home
    data: page.start
  /en/:
    template: home-en
    data: page.start-en

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: 'tag:-hash-en'
  /blog/en/:
    permalink: /en/blog/{slug}/
    template: index
    filter: 'tag:hash-en'

taxonomies:
  tag: /tag/{slug}/
