routes:
  /: 
    template: page
    data: page.start
  /blog/rss/:
    template: rss
    content_type: text/xml
  /sitemap/:
    template: sitemap
    content_type: text/xml

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: home
    filter: 'tag:-hash-pressemitteilung'
  /presse/mitteilungen/:
    permalink: /presse/mitteilungen/{year}/{slug}/
    template: search-pressemitteilungen
    filter: 'tag:hash-pressemitteilung'

taxonomies:
  tag: /tag/{slug}/
  author: /autor_in/{slug}/
