routes:
  /: home
  /blog/rss/:
    template: rss
    content_type: text/xml

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /autor/{slug}/
